{
    "library": {
        "HistoryInfo.js": false,
        "MasterInfo.js": false,
        "Search.js": false
    },
    "component": {
        "BaseChart.js": false,
        "CandleChart.js": false,
        "ChartView.js": false,
        "CompareChart.js": false,
        "CompareChartView.js": false,
        "EXCenterPivotView.js": false,
        "EXHogaGrid.js": false,
        "EXHogaView.js": false,
        "EXItemView.js": false,
        "EXJisooChart.js": false,
        "EXMiniChart.js": false,
        "EXMiniHoga.js": false,
        "EXSearchView.js": false,
        "EXSecureTextField.js": false,
        "MultiChartView.js": false
    },
    "event": {
        "CandleChartEvent.js": false,
        "ChartViewEvent.js": false,
        "CompareChartEvent.js": false,
        "EXBongEvent.js": false,
        "EXCenterPivotViewEvent.js": false,
        "EXHogaGridEvent.js": false,
        "EXHogaViewEvent.js": false,
        "EXItemViewEvent.js": false,
        "EXJisooChartEvent.js": false,
        "EXMiniChartEvent.js": false,
        "EXMiniHogaEvent.js": false,
        "EXSearchViewEvent.js": false,
        "EXSecureTextFieldEvent.js": false,
        "EXTriangleEvent.js": false
    },
    "style": {}
}